import React from 'react'
import Gallery from './Gallery.js'
import '../style/General.css'
import Navbar from './Navbar.js'
import santo1 from '../images/3- Pandemic/3.1.jpg'
//freddy1 (3.2) is a youtube link
import jose1 from '../images/3- Pandemic/3.3.jpg'
import riesbri1 from '../images/3- Pandemic/3.4.jpg'
import margaret1 from '../images/3- Pandemic/3.5.png'
import mia1 from '../images/3- Pandemic/3.6.jpeg'
import lale1 from '../images/3- Pandemic/3.7.png'

export default class Pandemic extends React.Component {
    constructor(props) {
    super(props);

    this.state = {
        list: [
            {link:"", type:"title", name:"PANDEMIC", artist:"", year:"2021", materials: "", dsc:""},
            {link:"", type:"text", name:"Sun Kissed", artist:"Santo Jacobsson (he/him)", year:"2021", materials:"Digital illustration", dsc:"Being an artist and illustrator living a multicultural and trans experience, Santo Jacobsson effectively combines modern aesthetics, personal experience, and societal topics into art that is both political and intimate at the same time. Sun Kissed is an excellent representation of Jacobsson’s socially relevant œuvre, depicting an individual who has become reliant on  electronics to feel connected to the rest of society. Each device features imagery of the sun to demonstrate how modern technology has  become a source of happiness by allowing us to engage digitally. Yet despite producing positive emotions, Jacobsson argues that technological happiness is artificial, and doesn’t provide the true freedom and complexity that genuine in-person interactions do. By including a window with closed blinds, Sun Kissed reveals how overuse of technology can contribute to claustrophobic feelings  that have been enhanced during the  COVID-19 pandemic."},
            {link:santo1, type:"image", name:"", artist:"", year:"", materials:"", dsc:""},
            {link:"", type:"text", name:"i just feel lost (without you)", artist:"Freddy Detchou (he/him)", year:"2020", materials:"Music Video and Song", dsc:"Freddy Detchou aka SUPER FREDDY is a Canadian artist and writer of Cameroonian origin whose musical practice combines a variety of genres to tell stories in his work. i just feel lost (without you) was released under Detchou’s artist name SUPER FREDDY, and features friend bnjmnevns. The track sprung from Detchou’s personal experience with loneliness caused by distance from loved ones during the pandemic. While the majority of Detchou’s support system lives in Canada, i just feel lost (without you) was penned while Detchou lived in New York, across a border that normally seems not far but became seemingly insurmountable because of COVID-19. With lyrics such as I just need time with you and I ain’t been home in awhile and these old streets feel so foreign, Detchou describes how the pandemic can turn a drive to see loved ones into a frustrating impossibility and  all of the emotions that come with this. The electronic production on the track references the heavy reliance on modern technology to sustain relationships suffering under the weight of distance, technology that, though helpful, still cannot stave off crushing loneliness."},
            {link:"https://www.youtube.com/embed/YCjHq_E7Wes", type:"video/mp4", name:"", artist:"", year:"", materials:"", dsc:""},
            {link:"", type:"text", name:"Se acabaron las Fiestas", artist:"José Galván Martínez", year:"2020", materials:"Acrylic on unstretched canvas", dsc:"José Galván Martínez, based in Oxnard, California, was born and raised in Mexico City. His work draws from childhood imagery and surroundings, as well as punk rock and anime culture. Se acabaron las Fiestas (translated literally as the festivities are over) uses these influences to depict how yearly traditions and moments are no longer the same following the pandemic. The work combines Mexican cultural imagery with new motifs relating to COVID-19: a woman dressed in traditional clothing dons a mask, sugar skulls paying homage to those lost to COVID mingle with the virus itself. While the vibrant colours and plentiful textures evoke the excitement that festivals usually inspire, the symbols of holidays such as Christmas and Día de Los Reyes seen as though from a distance in the eyes of the woman remind the viewer of all that has changed because of the pandemic. Additionally, the unraveling of the woman’s braids and ribbons calls to mind the slow transformation of all that was once normal into a new, post-pandemic era."},
            {link:jose1, type:"image", name:"", artist:"", year:"", materials:"", dsc:""},
            {link:"", type:"text", name:"2014", artist:"Riesbri", year:"2020", materials:"Acrylic on canvas", dsc:"2014 uses a real event that occurred in the titular year to discuss mental health. Depicting when the Pope released doves who were immediately attacked by a crow, 2014 speaks to a loss of hope linked with mental health deterioration. While Riesbri considered the idea behind this piece for years, the work only came to fruition at the beginning of the pandemic. The murder of crows, which seems to grow as  gets closer to the piece, bombard the viewer with unease. Being negative omens and symbols of ill fortune, the abundance of these birds dominates the viewer’s sight, almost removing attention from the one positive symbol in the work: the dove. Even when concentrating on the dove, the viewer cannot help but feel a new wave of despair wash over them as the bird struggles in flight. Through 2014, Riesbri perfectly captures the demolition of harmony and well-being experienced by many during the pandemic, as well as the immense feeling of dread that has negatively impacted everyone’s mental stability as a result, including that of the artist."},
            {link:riesbri1, type:"image", name:"", artist:"", year:"", materials:"", dsc:""},
            {link:"", type:"text", name:"Metaphorizing the merlots my mother drops off", artist:"Margaret Zhang (they/them)", year:"2020", materials:"Poetry", dsc:"Like many, at the beginning of the pandemic Margaret Zhang  temporarily left their apartment to return to live in their parents’ house. And, like many relationships during the pandemic, this move reignited tensions between Zhang and their mother, heightened by the restrictive nature of lockdown. In Metaphorizing the merlots my mother drops off during quarantine, Zhang reminisces about past history between their mother and themself, highlighting teenage memories and difficult experiences. The result is a moving reflection speaking to one of the most influential relationships in Zhang’s life and the way it has evolved as a result of the distance and need for human connection brought on by the pandemic."},
            {link:margaret1, type:"poetry", name:"", artist:"", year:"", materials:"", dsc:""},
            {link:"", type:"text", name:"5 Steps to Freedom", artist:"Mia Ari (they/them)", year:"2020", materials:"Oil on canvas", dsc:"Through its apocalyptic color palette and cramped sense of space, 5 Steps to Freedom describes the desire to escape that Mia Ari experienced near the beginning of the pandemic. The work oozes anxiety: dark colors and blurry forms are seen as though through a lens; vignetting gives the impression of panic-driven tunnel vision. While the viewer can experience the piece externally, perspective allows them to project themselves into the work, trapped just below the ascending figure whose (almost too slow) procession blocks the way to the only opening to liberation.  In this sense, one can interact with the need to escape on a personal level, while also understanding the artist’s own feelings independently. Painted at a time when changes in personal relationships, a move to a new place, and lockdown from COVID-19 weighed heavily on the Ari, 5 Steps to Freedom successfully represents emotions felt by the artist during a difficult time, as well as showing that there is always a light at the end of the proverbial tunnel."},
            {link:mia1, type:"image", name:"", artist:"", year:"", materials:"", dsc:""},
            {link:"", type:"text", name:"I’ll wake him when the apocalypse ends", artist:"Lale Ceylan (she/her)", year:"2021", materials:"Graphite on paper", dsc:"I’ll wake him when the apocalypse ends explores the silence of the past year. Despite the pandemic, political tension, and civil rights movements of 2020, the year was punctuated by quiet moments at home resulting from lockdown. Ceylan’s work depicts two sleeping individuals, speaking to how many days during the pandemic are spent in an endless cycle of working from home, watching TV programmes, and sleeping. Ceylan’s work depicts both her partner and young nephew respectively, with the images working to juxtapose the similar yet varied experiences of children vs. adults, as well as the present vs. the future. Though adults are struggling with how to handle the present situation, it is children who will also feel a major impact for years to come. Yet while this has been hard on all of us, the work also presents brief moments of peace found during this stressful time. Both portraits look so calm and at ease in their repose, that Ceylan’s reaction is to leave the subjects resting until the apocalypse ends."},
            {link:lale1, type:"image", name:"", artist:"", year:"", materials:"", dsc:""},
            {link:"/racism-govnernment", type:"link", name:"RACISM/GOVERNMENT", artist:"", year:"", materials:"", dsc:""},
        ],
    }
}


    render() {  
    return (
        <div className="pandemic-bg">
            <Navbar></Navbar>
            <Gallery list={this.state.list}/>
        </div>
    );
    }
}